### ISSUE TITLE
Implement kill command

### ISSUE THREAD

**Issue by piotrminkina** [bytegust/spm#11]
I think `kill` command with optional `-s` parameter (to specify signal type) will be helpful for the following case:

Example `Procfile`:
```
confd: exec confd -backend etcd -watch -config-file myconfig.toml
nginx: exec nginx -g 'daemon off;'
```

Example `myconfig.toml`:
```toml
[template]
src = "/etc/nginx/nginx.conf.tmpl"
dest = "/etc/nginx/nginx.conf"
reload_cmd = "spm kill -s HUP nginx"
```

Thanks for this command we can send some signals to running jobs, without known its current pid.

Is it possible that this feature will be implemented?
